services:

  llm:
    ports:
      - "2000:80"
  ollama:
    ports:
      - "11434:11434"
  identifier:
    restart: "no"
    ports:
      - "80:80"
  virtuoso:
    restart: "no"
    ports:
      - "8890:8890"
  # Override the frontend and run it locally instead to avoid need to build image
  frontend:
    restart: "no"
  database:
    restart: "no"
  dispatcher:
    restart: "no"
  resource:
    restart: "no"
  migrations:
    restart: "no"
