services:
  identifier:
    restart: "no"
    ports:
      - "80:80"
  database:
    restart: "no"
    ports:
      - "8890:8890"
  # Override the frontend and run it locally instead to avoid need to build image
  frontend:
    restart: "no"
  dispatcher:
    restart: "no"
  resource:
    restart: "no"
  migrations:
    restart: "no"
