services:

  llm:
    ports:
      - "2000:80"
  ollama:
    ports:
      - "11434:11434"
  identifier:
    ports:
      - "80:80"
  database:
    ports:
      - "8890:8890"
  # Override the frontend and run it locally instead to avoid need to build image
  frontend:
    image: node:20-slim
