services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
    restart: always
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    restart: always
  virtuoso:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
  resource:
    image: semtech/mu-cl-resources:1.25.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    restart: always
  frontend:
    # Skip docker hub and just build it, it's a hackathon...
    build: ../frontend-ai-hackathon-group-4
    restart: always
  migrations:
    image: semtech/mu-migrations-service:0.6.0
    environment:
      MU_SPARQL_TIMEOUT: "300"
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
  database:
    image: semtech/sparql-parser:0.0.8
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      DATABASE_OVERLOAD_RECOVERY: "true"
      DATABASE_COMPATIBILITY: "Virtuoso"
      # Note: not sure wether it gets picked up properly, it is meant for healing-process which may make
      # heavy queries
      QUERY_MAX_PROCESSING_TIME: 605000
      QUERY_MAX_EXECUTION_TIME: 605000
    volumes:
      - ./config/cl-authorization:/config
      - ./data/mu-auth:/data
    labels:
      - "logging=true"
    restart: always
