services:
  llm:
    ports:
      - "2000:80"
    restart: "no"
  ollama:
    ports:
      - "11434:11434"
    restart: "no"
  pdfsummarization:
    ports:
      # we should not do this but for hackathon purposes it's fine for now
      - 9090:9090
    restart: "no"
  identifier:
    ports:
      - "80:80"
    restart: "no"
  database:
    ports:
      - "8890:8890"
    restart: "no"
  # Override the frontend and run it locally instead to avoid need to build image
  frontend:
    image: node:20-slim
    restart: "no"
