@startuml
set namespaceSeparator none
class "agents"
"agents" : name
"agents" --> "*" "annotations" : creator > 
class "annotations"
"annotations" : body
"annotations" : created
"annotations" : motivation
"annotations" --> "1" "annotation-types" : annotation-type > 
"annotations" --> "1" "agents" : creator > 
"annotations" --> "1" "besluiten" : about > 
class "aanduidingsobjects"
"aanduidingsobjects" : title
"aanduidingsobjects" : description
"aanduidingsobjects" : identifier
"aanduidingsobjects" : style
"aanduidingsobjects" : creation
"aanduidingsobjects" --> "1" "address-representations" : address > 
"aanduidingsobjects" --> "1" "concepts" : typology > 
class "concepts"
"concepts" : title
class "address-representations"
"address-representations" : municipality-name
"address-representations" : province
"address-representations" : street-name
"address-representations" : postal-code
"address-representations" : bus-number
"address-representations" --> "*" "aanduidingsobjects" : references > 
"NIL" <|-- "address-representations"
class "NIL"
class "annotation-types"
"annotation-types" : title
"concepts" <|-- "annotation-types"
class "besluiten"
"besluiten" : title
"besluiten" --> "1" "concepts" : kind > 
@enduml
